[package]
name = "hanoi-speedrapp"
description = "Tower of Hanoi desktop app for speedrunning"
repository = "https://github.com/SpeckyYT/hanoi-speedrapp"
version = "0.2.0"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = { version = "3.4.0", default-features = false }
arrayvec = { version = "0.7.4", features = ["serde"] }
cached = "0.53.1"
chrono = { version = "0.4.38", features = ["serde"] }
colorgrad = "0.7.0"
eframe = { version = "0.28.1", features = ["persistence", "puffin", "wgpu"] }
egui_dnd = "0.9.1"
egui_extras = "0.28.1"
egui_plot = "0.28.1"
indoc = "2.0.5"
once_cell = "1.19.0"
pretty-duration = "0.1.1"
puffin = "0.19.0"
puffin_http = "0.16.0"
serde = { version = "1.0.200", features = ["derive"] }
serde_with = "3.9.0"
strum = { version = "0.26.2", features = ["derive"] }
