[package]
name = "hanoi-speedrapp"
description = "Tower of Hanoi desktop app for speedrunning"
repository = "https://github.com/SpeckyYT/hanoi-speedrapp"
version = "0.2.0"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = { version = "3.4.1", default-features = false }
arrayvec = { version = "0.7.6", features = ["serde"] }
cached = "0.54.0"
chrono = { version = "0.4.38", features = ["serde"] }
colorgrad = "0.7.0"
eframe = { version = "0.29.1", features = ["persistence", "puffin", "glow"] }
egui_dnd = "0.10.0"
egui_extras = "0.29.1"
egui_plot = "0.29.0"
indoc = "2.0.5"
once_cell = "1.20.2"
pretty-duration = "0.1.1"
puffin = "0.19.1"
puffin_http = "0.16.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_with = "3.11.0"
strum = { version = "0.26.3", features = ["derive"] }
