[package]
name = "hanoi-speedrapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
eframe = "0.27.2"
once_cell = "1.19.0"
pretty-duration = "0.1.1"
