[package]
name = "hanoi-speedrapp"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.4", features = ["serde"] }
eframe = { version = "0.27.2", features = ["persistence"] }
once_cell = "1.19.0"
pretty-duration = "0.1.1"
serde = { version = "1.0.200", features = ["derive"] }
strum = { version = "0.26.2", features = ["derive"] }
