[package]
name = "hanoi-speedrapp"
description = "Tower of Hanoi desktop app for speedrunning"
repository = "https://github.com/SpeckyYT/hanoi-speedrapp"
version = "0.5.1"
edition = "2024"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.6", features = ["serde"] }
cached = "0.59.0"
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6.0", features = ["derive"] }
colorgrad = "0.8.0"
eframe = { version = "0.34.0", features = ["persistence"] }
egui_dnd = "0.15.0"
egui_extras = "0.34.0"
egui_plot = "0.35.0"
indoc = "2.0.7"
itertools = "0.14.0"
num-to-words = "0.1.1"
pretty-duration = "0.1.1"
profiling = { version = "1.0.17", features = ["profile-with-puffin"] }
puffin = "0.20.0"
puffin_http = "0.17.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = "3.18.0"
strum = { version = "0.28.0", features = ["derive"] }

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
panic = "abort"
