on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: CI
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
jobs:
  build:
    runs-on: ${{ matrix.target }}
    strategy:
      matrix:
        target: [
          windows-latest,
          ubuntu-latest,
          macos-latest,
          # wasm32-wasi,
        ]
        rust: [stable] # beta, nightly, 1.80.0
    steps:
      - uses: actions/checkout@v2
        with: {submodules: true}
      - uses: actions-rs/toolchain@v1
        with: {profile: minimal, toolchain: '${{ matrix.rust }}', override: true}
      - run: cargo build
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: {profile: minimal, toolchain: beta, override: true, components: clippy}
      - run: cargo clippy
