on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
name: CI
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  build:
    runs-on: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - if: ${{ github.event_name != 'release' }}
        run: cargo build
      - if: ${{ github.event_name == 'release' }}
        run: cargo build --release
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/') 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref }}
          # tag: ${{ github.ref }}_release # not required apparently?
          generateReleaseNotes: true
          allowUpdates: true
          body: Release of hanoi-speedrapp
          artifacts: |
            target/debug/hanoi-speedrapp
            target/debug/hanoi-speedrapp.*
            target/release/hanoi-speedrapp
            target/release/hanoi-speedrapp.*
    name: Build and Release
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
          components: clippy
      - run: cargo clippy
    name: Clippy
